[dev]
    pghost     = "192.168.3.221"
    pgport     = 5432
    pguser     = "postgres"
    pgpassword = "2xxiiill"
    pgdbname   = "pm"

    fmhost     = "192.168.3.221"
    fmport     = 5432
    fmuser     = "postgres"
    fmpassword = "2xxiiill"
    fmdbname   = "qeindex"

    myhost     = "192.168.3.121"
    myport     = 33060
    myuser     = "root"
    mypassword = "zRq*6CZX"
    mydbname   = "news"

    elastic = "http://192.168.3.131:9200"
[prod]
    pghost     = "192.168.3.221"
    pgport     = 5432
    pguser     = "postgres"
    pgpassword = "2xxiiill"
    pgdbname   = "pm"

    fmhost     = "192.168.3.221"
    fmport     = 5432
    fmuser     = "postgres"
    fmpassword = "2xxiiill"
    fmdbname   = "qeindex"

    myhost     = "192.168.3.121"
    myport     = 33060
    myuser     = "root"
    mypassword = "zRq*6CZX"
    mydbname   = "news"

    elastic = "http://192.158.3.221:9200"